version: '3.6'

services:
  api:
    container_name: pyphrasy_api
    environment:
      DEBUG: 'true'
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: unless-stopped